image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Update and upgrade packages
    init: |
      sudo apt update
      sudo apt upgrade -y
      curl ifconfig.me > base_web_app/local.ip
  - name: Initalise terraform
    init: |
      cp ./commands/bash_aliases ~/.bash_aliases
      source ~/.bashrc
    command: |
      cd base_web_app
      terraform init
      terraform plan

vscode:
  extensions:
    - hashicorp.terraform