image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Initalise terraform
    init: |
      # export AWS_DEFAULT_REGION="eu-central-1"
      cp ./commands/bash_aliases ~/.bash_aliases
      source ~/.bashrc
    command: |
      cd base_web_app
      terraform init
      terraform plan

vscode:
  extensions:
    - hashicorp.terraform